language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false
addons:
  apt:
    packages:
        - pandoc
        - graphviz

cache:
  directories:
    - $HOME/.cache/pip

env:
    global:
        - DEPENDS="ipython[notebook] sphinx matplotlib six"
        - PKG_NAME=nb2plots
        - INSTALL_TYPE="pip"

python:
    - 3.4
    - 3.5
    - 3.6
    - 3.8

matrix:
  include:
    - python: 2.7
      env:
        - COVER_ARGS="--cov=$PKG_NAME"
        - DOCTEST_ARGS="--doctest-modules"
    # Check finding dependencies from pip
    - python: 2.7
      env:
        - DEPENDS=
    - python: 3.6
      env:
        - DEPENDS=
    - python: 3.5
      env:
        - DOCTEST_ARGS="--doctest-modules"
    # Absolute minimum dependencies
    # Check also requirements.txt
    - python: 2.7
      env:
          - DEPENDS="ipython[notebook]==4.0.0 sphinx==1.4 matplotlib==2.0 six==1.10 numpy==1.7.1"
    - python: 2.7
      env:
          - DEPENDS="ipython[notebook] sphinx==1.4.3 matplotlib"
    - python: 2.7
      env:
        - INSTALL_TYPE=setup
    - python: 2.7
      env:
        - INSTALL_TYPE=sdist
    - python: 2.7
      env:
        - INSTALL_TYPE=wheel
    - python: 2.7
      env:
        - INSTALL_TYPE=requirements
        - DEPENDS=
    - python: 3.5
      env:
        - BUILD_DOC=1
    # Test pre-release versions of everything
    - python: 3.8
      env:
        - EXTRA_PIP_FLAGS="--pre"
    - python: 3.5
      env:
          - DEPENDS="ipython[notebook] sphinx==1.7.6 matplotlib"

before_install:
    - source tools/travis_tools.sh
    - pip install -U virtualenv
    - virtualenv --python=python venv
    - source venv/bin/activate
    - python -m pip install --upgrade pip wheel
    - python --version  # just to check
    - pip install pytest mock scripttester # always
    - if [ -n "$DEPENDS" ]; then
      pip install $EXTRA_PIP_FLAGS $DEPENDS;
      fi

install:
    - |
      if [ "$INSTALL_TYPE" == "pip" ]; then
          pip install .
      elif [ "$INSTALL_TYPE" == "setup" ]; then
          python setup.py install
      elif [ "$INSTALL_TYPE" == "sdist" ]; then
        python setup.py egg_info  # check egg_info while we're here
        python setup.py sdist
        pip install dist/*.tar.gz
      elif [ "$INSTALL_TYPE" == "wheel" ]; then
        pip install wheel
        python setup.py bdist_wheel
        pip install dist/*.whl
      elif [ "$INSTALL_TYPE" == "requirements" ]; then
        pip install -r requirements.txt
        python setup.py install
      fi

script:
    - |
      if [ -n "$BUILD_DOC" ]; then
        # Build documentation
        pip install -r doc-requirements.txt
        cd doc
        # Make warnings function as errors on Sphinx build
        export SPHINXOPTS='-W'
        make html
        make doctest
      else
        # Change into an innocuous directory and find tests from installation
        mkdir for_testing
        cd for_testing
        if [ -n "$COVER_ARGS" ]; then
          cp ../.coveragerc .;
          pip install pytest-cov
          pip install coveralls
        fi
        py.test $COVER_ARGS $DOCTEST_ARGS --pyargs $PKG_NAME
      fi

after_success:
    - if [ -n "$COVER_ARGS" ]; then codecov; fi
