on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

name: Run tox tests

jobs:
  tox_test:
    name: Run tox tests
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    - name: Run tox tests
      id: test
      uses: fedora-python/tox-github-action@master
      with:
        tox_env: ${{ matrix.tox_env }}
        dnf_install: /usr/bin/pandoc
    - name: Upload HTML coverage report
      uses: actions/upload-artifact@v2
      with:
        name: html-report
        path: htmlcov
        if-no-files-found: ignore
    strategy:
      matrix:
        tox_env: [
          # This list has to be maintained manually :(
          # You can get it from `tox -l | sed "s/$/,/"`
          py37,
          py38,
          py39,
          py310,
        ]

    # Use GitHub's Linux Docker host
    runs-on: ubuntu-latest
